
import './App.css';

import Coursel from './Componets/Coursel';
import Navbar from './Componets/Navbar';
import Footer from './Componets/Footer';
import SmallCoursel from './Componets/SmallCoursel';
import { Amplify } from 'aws-amplify';
import awsExports from './aws-exports'; // Generated by Amplify
Amplify.configure(awsExports);
import React, { useEffect } from "react";
import { Auth } from "aws-amplify";



function App() {

  useEffect(() => {
    // Check if user is already authenticated
    Auth.currentSession()
      .then(session => {
        console.log("ID Token:", session.getIdToken().getJwtToken());
        console.log("Access Token:", session.getAccessToken().getJwtToken());
        console.log("Refresh Token:", session.getRefreshToken().getToken());
      })
      .catch(err => {
        console.error("User is not logged in:", err);
      });
  }, []);
  return (
    <div>
   <Navbar/>
   <Coursel/>
   <SmallCoursel/>
 
   <Footer/>
   </div>
  );
}

export default App;
